In [1642]:
import numpy as np
from numpy.linalg import inv
import rppy

np.set_printoptions(precision=8)

In [1643]:
def monoclinic_bicubic_coeffs(s1, s2, p, C):
    c11 = C[0][0]
    c22 = C[1][1]
    c33 = C[2][2]
    c44 = C[3][3]
    c55 = C[4][4]
    c66 = C[5][5]
    c12 = C[0][1]
    c13 = C[0][2]
    c23 = C[1][2]
    c16 = C[0][5]
    c26 = C[1][5]
    c36 = C[2][5]
    c45 = C[3][4]
    A = (c33*c44*c55 - c33*c45**2)
    B = (c11*c33*c44*s1**2 - 2*c12*c33*c45*s1*s2 - c13**2*c44*s1**2 + 
         2*c13*c23*c45*s1*s2 - 2*c13*c36*c44*s1*s2 + 2*c13*c36*c45*s1**2 - 
         2*c13*c44*c55*s1**2 + 2*c13*c45**2*s1**2 + 2*c16*c33*c44*s1*s2 - 
         2*c16*c33*c45*s1**2 + c22*c33*c55*s2**2 - c23**2*c55*s2**2 + 
         2*c23*c36*c45*s2**2 - 2*c23*c36*c55*s1*s2 - 2*c23*c44*c55*s2**2 + 
         2*c23*c45**2*s2**2 - 2*c26*c33*c45*s2**2 + 2*c26*c33*c55*s1*s2 + 
         c33*c44*c66*s2**2 - c33*c44*p - 2*c33*c45*c66*s1*s2 + 
         c33*c55*c66*s1**2 - c33*c55*p - c36**2*c44*s2**2 + 
         2*c36**2*c45*s1*s2 - c36**2*c55*s1**2 - 4*c36*c44*c55*s1*s2 + 
         4*c36*c45**2*s1*s2 - c44*c55*p + c45**2*p)
    C = (c11*c22*c33*s1**2*s2**2 - c11*c23**2*s1**2*s2**2 - 2*c11*c23*c36*s1**3*s2 - 
         2*c11*c23*c44*s1**2*s2**2 - 2*c11*c23*c45*s1**3*s2 + 2*c11*c26*c33*s1**3*s2 + 
         c11*c33*c66*s1**4 - c11*c33*p*s1**2 - c11*c36**2*s1**4 - 
         2*c11*c36*c44*s1**3*s2 - 2*c11*c36*c45*s1**4 + c11*c44*c55*s1**4 - 
         c11*c44*p*s1**2 - c11*c45**2*s1**4 - c12**2*c33*s1**2*s2**2 + 
         2*c12*c13*c23*s1**2*s2**2 + 2*c12*c13*c36*s1**3*s2 + 2*c12*c13*c44*s1**2*s2**2 + 
         2*c12*c13*c45*s1**3*s2 - 2*c12*c16*c33*s1**3*s2 + 2*c12*c23*c36*s1*s2**3 + 
         2*c12*c23*c45*s1*s2**3 + 2*c12*c23*c55*s1**2*s2**2 - 2*c12*c26*c33*s1*s2**3 - 
         2*c12*c33*c66*s1**2*s2**2 + 2*c12*c36**2*s1**2*s2**2 + 2*c12*c36*c44*s1*s2**3 + 
         4*c12*c36*c45*s1**2*s2**2 + 2*c12*c36*c55*s1**3*s2 + 2*c12*c44*c55*s1**2*s2**2 - 
         2*c12*c45**2*s1**2*s2**2 + 2*c12*c45*p*s1*s2 - c13**2*c22*s1**2*s2**2 - 
         2*c13**2*c26*s1**3*s2 - c13**2*c66*s1**4 + c13**2*p*s1**2 + 
         2*c13*c16*c23*s1**3*s2 + 2*c13*c16*c36*s1**4 + 2*c13*c16*c44*s1**3*s2 + 
         2*c13*c16*c45*s1**4 - 2*c13*c22*c36*s1*s2**3 - 2*c13*c22*c45*s1*s2**3 - 
         2*c13*c22*c55*s1**2*s2**2 + 2*c13*c23*c26*s1*s2**3 + 2*c13*c23*c66*s1**2*s2**2 - 
         2*c13*c26*c36*s1**2*s2**2 + 2*c13*c26*c44*s1*s2**3 - 2*c13*c26*c45*s1**2*s2**2 - 
         4*c13*c26*c55*s1**3*s2 + 2*c13*c36*p*s1*s2 + 2*c13*c44*c66*s1**2*s2**2 + 
         2*c13*c45*p*s1*s2 - 2*c13*c55*c66*s1**4 + 2*c13*c55*p*s1**2 - 
         c16**2*c33*s1**4 + 2*c16*c22*c33*s1*s2**3 - 2*c16*c23**2*s1*s2**3 - 
         2*c16*c23*c36*s1**2*s2**2 - 4*c16*c23*c44*s1*s2**3 - 2*c16*c23*c45*s1**2*s2**2 + 
         2*c16*c23*c55*s1**3*s2 + 2*c16*c26*c33*s1**2*s2**2 - 2*c16*c33*p*s1*s2 - 
         2*c16*c36*c44*s1**2*s2**2 + 2*c16*c36*c55*s1**4 + 4*c16*c44*c55*s1**3*s2 - 
         2*c16*c44*p*s1*s2 - 4*c16*c45**2*s1**3*s2 + 2*c16*c45*p*s1**2 + 
         c22*c33*c66*s2**4 - c22*c33*p*s2**2 - c22*c36**2*s2**4 - 
         2*c22*c36*c45*s2**4 - 2*c22*c36*c55*s1*s2**3 + c22*c44*c55*s2**4 - 
         c22*c45**2*s2**4 - c22*c55*p*s2**2 - c23**2*c66*s2**4 + 
         c23**2*p*s2**2 + 2*c23*c26*c36*s2**4 + 2*c23*c26*c45*s2**4 + 
         2*c23*c26*c55*s1*s2**3 + 2*c23*c36*p*s1*s2 - 2*c23*c44*c66*s2**4 + 
         2*c23*c44*p*s2**2 + 2*c23*c45*p*s1*s2 + 2*c23*c55*c66*s1**2*s2**2 - 
         c26**2*c33*s2**4 - 2*c26*c33*p*s1*s2 + 2*c26*c36*c44*s2**4 - 
         2*c26*c36*c55*s1**2*s2**2 + 4*c26*c44*c55*s1*s2**3 - 4*c26*c45**2*s1*s2**3 + 
         2*c26*c45*p*s2**2 - 2*c26*c55*p*s1*s2 - c33*c66*p*s1**2 - 
         c33*c66*p*s2**2 + c33*p**2 + c36**2*p*s1**2 + 
         c36**2*p*s2**2 + 2*c36*c44*p*s1*s2 + 2*c36*c45*p*s1**2 + 
         2*c36*c45*p*s2**2 + 2*c36*c55*p*s1*s2 + 4*c44*c55*c66*s1**2*s2**2 - 
         c44*c55*p*s1**2 - c44*c55*p*s2**2 - c44*c66*p*s2**2 + 
         c44*p**2 - 4*c45**2*c66*s1**2*s2**2 + c45**2*p*s1**2 + 
         c45**2*p*s2**2 + 2*c45*c66*p*s1*s2 - c55*c66*p*s1**2 + c55*p**2)
    D = (c11*c22*c44*s1**2*s2**4 + 2*c11*c22*c45*s1**3*s2**3 + c11*c22*c55*s1**4*s2**2 -
         c11*c22*p*s1**2*s2**2 + 2*c11*c26*c44*s1**3*s2**3 + 4*c11*c26*c45*s1**4*s2**2 +
         2*c11*c26*c55*s1**5*s2 - 2*c11*c26*p*s1**3*s2 + c11*c44*c66*s1**4*s2**2 -
         c11*c44*p*s1**2*s2**2 + 2*c11*c45*c66*s1**5*s2 - 2*c11*c45*p*s1**3*s2 +
         c11*c55*c66*s1**6 - c11*c55*p*s1**4 - c11*c66*p*s1**4 +
         c11*p**2*s1**2 - c12**2*c44*s1**2*s2**4 - 2*c12**2*c45*s1**3*s2**3 -
         c12**2*c55*s1**4*s2**2 + c12**2*p*s1**2*s2**2 - 2*c12*c16*c44*s1**3*s2**3 -
         4*c12*c16*c45*s1**4*s2**2 - 2*c12*c16*c55*s1**5*s2 + 2*c12*c16*p*s1**3*s2 -
         2*c12*c26*c44*s1*s2**5 - 4*c12*c26*c45*s1**2*s2**4 - 2*c12*c26*c55*s1**3*s2**3 +
         2*c12*c26*p*s1*s2**3 - 2*c12*c44*c66*s1**2*s2**4 - 4*c12*c45*c66*s1**3*s2**3 -
         2*c12*c55*c66*s1**4*s2**2 + 2*c12*c66*p*s1**2*s2**2 - c16**2*c44*s1**4*s2**2 -
         2*c16**2*c45*s1**5*s2 - c16**2*c55*s1**6 + c16**2*p*s1**4 +
         2*c16*c22*c44*s1*s2**5 + 4*c16*c22*c45*s1**2*s2**4 + 2*c16*c22*c55*s1**3*s2**3 -
         2*c16*c22*p*s1*s2**3 + 2*c16*c26*c44*s1**2*s2**4 + 4*c16*c26*c45*s1**3*s2**3 +
         2*c16*c26*c55*s1**4*s2**2 - 2*c16*c26*p*s1**2*s2**2 - 2*c16*c44*p*s1*s2**3 -
         4*c16*c45*p*s1**2*s2**2 - 2*c16*c55*p*s1**3*s2 + 2*c16*p**2*s1*s2 +
         c22*c44*c66*s2**6 - c22*c44*p*s2**4 + 2*c22*c45*c66*s1*s2**5 -
         2*c22*c45*p*s1*s2**3 + c22*c55*c66*s1**2*s2**4 - c22*c55*p*s1**2*s2**2 -
         c22*c66*p*s2**4 + c22*p**2*s2**2 - c26**2*c44*s2**6 -
         2*c26**2*c45*s1*s2**5 - c26**2*c55*s1**2*s2**4 + c26**2*p*s2**4 -
         2*c26*c44*p*s1*s2**3 - 4*c26*c45*p*s1**2*s2**2 - 2*c26*c55*p*s1**3*s2 +
         2*c26*p**2*s1*s2 - c44*c66*p*s1**2*s2**2 - c44*c66*p*s2**4 +
         c44*p**2*s2**2 - 2*c45*c66*p*s1**3*s2 - 2*c45*c66*p*s1*s2**3 +
         2*c45*p**2*s1*s2 - c55*c66*p*s1**4 - c55*c66*p*s1**2*s2**2 +
         c55*p**2*s1**2 + c66*p**2*s1**2 + c66*p**2*s2**2 - p**3)
    return(A, B, C, D)

def christoffel(C, s):
    CM = np.zeros(shape=(3, 3))
    CM[0][0] = C[0][0]*s[0]**2 + C[5][5]*s[1]**2 + C[4][4]*s[2]**2 + 2*C[0][5]*s[0]*s[1]
    CM[0][1] = C[0][5]*s[0]**2 + C[1][5]*s[1]**2 + C[3][4]*s[2]**2 + (C[0][1]+C[5][5])*s[0]*s[1]
    CM[0][2] = (C[0][2]+C[4][4])*s[0]*s[2] + (C[2][5]+C[3][4])*s[1]*s[2]
    CM[1][0] = C[0][5]*s[0]**2 + C[1][5]*s[1]**2 + C[3][4]*s[2]**2 + (C[0][1]+C[5][5])*s[0]*s[1]
    CM[1][1] = C[5][5]*s[0]**2 + C[1][1]*s[1]**2 + C[3][3]*s[2]**2 + 2*C[1][5]*s[0]*s[1]
    CM[1][2] = (C[2][5]+C[3][4])*s[0]*s[2] + (C[1][2]+C[3][3])*s[1]*s[2]
    CM[2][0] = (C[0][2]+C[4][4])*s[0]*s[2] + (C[2][5]+C[3][4])*s[1]*s[2]
    CM[2][1] = (C[2][5]+C[3][4])*s[0]*s[2] + (C[3][3]+C[1][2])*s[1]*s[2]
    CM[2][2] = C[4][4]*s[0]**2 + C[3][3]*s[1]**2+C[2][2]*s[2]**2 + 2*C[3][4]*s[0]*s[1]

    return(CM)

In [1644]:
phi = np.radians(30)
theta = np.radians(40)

p1 = 1400
chi1 = 0
C1 = np.zeros(shape=(6, 6))
C1 = [[15.12e9, 5.29e9, 6.26e9, 0,      0,      0],
      [5.29e9, 10.89e9, 6.46e9, 0,      0,      0],
      [6.26e9,  6.46e9, 9.36e9, 0,      0,      0],
      [0,       0,      0,      2.00e9, 0,      0],
      [0,       0,      0,      0,      2.09e9, 0],
      [0,       0,      0,      0,      0,      4.26e9]]

p2 = 1840
chi2 = 0
C2 = np.zeros(shape=(6, 6))
C2 = [[28.52e9,  7.70e9,  6.00e9, 0,      0,      0],
      [ 7.70e9, 15.21e9,  7.65e9, 0,      0,      0],
      [ 6.00e9,  7.65e9, 10.65e9, 0,      0,      0],
      [ 0,       0,       0,      2.23e9, 0,      0],
      [ 0,       0,       0,      0,      2.41e9, 0],
      [ 0,       0,       0,      0,      0,      5.71e9]]

In [1645]:
# Construct rotation matrices to properly align the
# HTI porion of the orthorhombic anisotropy.
schi = np.sin(chi1)
cchi = np.cos(chi1)
G1 = [[cchi**2, schi**2, 0, 0, 0, 2*cchi*schi],
               [schi**2, cchi**2, 0, 0, 0, -2*schi*cchi],
               [0, 0, 1, 0, 0, 0],
               [0, 0, 0, cchi, -schi, 0],
               [0, 0, 0, schi, cchi,  0],
               [-cchi*schi, cchi*schi, 0, 0, 0, cchi**2 - schi**2]]
G1 = np.asarray(G1)

schi = np.sin(chi2)
cchi = np.cos(chi2)
G2 = np.zeros(shape=(6, 6))
G2 = [[cchi**2, schi**2, 0, 0, 0, 2*cchi*schi],
      [schi**2, cchi**2, 0, 0, 0, 2*schi*cchi],
      [0, 0, 1, 0, 0, 0],
      [0, 0, 0, cchi, -schi, 0],
      [0, 0, 0, schi, cchi,  0],
      [-cchi*schi, cchi*schi, 0, 0, 0, cchi**2 - schi**2]]
G2 = np.asarray(G2)

# Rotate stiffness matrices
C1 = G1.dot(C1).dot(G1.T)
C2 = G2.dot(C2).dot(G2.T)

##### QC Output
print('Rotation Matrix G1')
print(G1)
print('Rotated Stiffness Matrix C1')
print(C1)

Rotation Matrix G1
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1. -0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [-0.  0.  0.  0.  0.  1.]]
Rotated Stiffness Matrix C1
[[  1.51200000e+10   5.29000000e+09   6.26000000e+09   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  5.29000000e+09   1.08900000e+10   6.46000000e+09   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  6.26000000e+09   6.46000000e+09   9.36000000e+09   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.00000000e+09
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    2.09000000e+09   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   4.26000000e+09]]


In [1646]:
########################################
# SLOWNESS VECTOR OF THE INCIDENT WAVE
########################################

# Construct Christoffel matrices in the velocity form as the first step
# towards determining the phase velocity and phase polarization vectors
# in the direction of propagation (that is, the slowness vector of the incident phase).

# Propagation vector (directional, no velocity information)
n = np.array([np.cos(phi)*np.sin(theta), np.sin(phi)*np.sin(theta), np.cos(theta)])

# Construct Christoffel matrix 
L = christoffel(C1, n)

# Compute eigenvectors and eigenvalues of Christoffel matrix.
w, v = np.linalg.eig(L/p1)

vp1 = np.sqrt(np.max(w)) # quasi-P velocity of the upper medium, in the direction of propagation.
s = n / vp1 # Slowness vector using derived quasi-P velocity.

##### QC Output
print('n1', n)
print('L', L/p1)
print('vp1', vp1)
print('s', s)

n1 [ 0.5566704   0.3213938   0.76604444]
L [[ 4537078.23120201  1220424.63469076  2543375.80064389]
 [ 1220424.63469076  2584726.16571064  1487763.14115773]
 [ 2543375.80064389  1487763.14115773  4533510.47701289]]
vp1 2790.10567532
s [ 0.00019952  0.00011519  0.00027456]


In [1647]:
########################################
# SLOWNESS VECTORS OF REFLECTED WAVES
########################################

# Compute the coefficients of the bicubic equation from the stiffness
# matrix of the upper layer, density, and the two horizontal components
# of slowness.
A, B, C, D = monoclinic_bicubic_coeffs(s[0], s[1], p1, C1)

# Input the computed coefficients and solve the bicubic polynomial
z = np.sort(np.roots(np.array([A, B, C, D])))

s1P = np.array([s[0], s[1], np.sqrt(np.abs(z[0]))])
s1S = np.array([s[0], s[1], np.sqrt(np.abs(z[1]))])
s1T = np.array([s[0], s[1], np.sqrt(np.abs(z[2]))])

##### QC Output
print('Coeffs')
print(A, B, C, D)
print('Roots')
print(z)
print('s1P', s1P)
print('s1T', s1S)
print('s1S', s1T)

Coeffs
3.91248e+28 -4.805501492e+22 1.63598376931e+16 -976924786.499
Roots
[  7.53818216e-08   5.44242769e-07   6.08624881e-07]
s1P [ 0.00019952  0.00011519  0.00027456]
s1T [ 0.00019952  0.00011519  0.00073773]
s1S [ 0.00019952  0.00011519  0.00078014]


In [1648]:
########################################
# SLOWNESS VECTORS OF TRANSMITTED WAVES
########################################

# Compute the coefficients of the bicubic equation from the stiffness
# matrix of the upper layer, density, and the two horizontal components
# of slowness.
A, B, C, D = monoclinic_bicubic_coeffs(s[0], s[1], p2, C2)

# Input the computed coefficients and solve the bicubic polynomial
z = np.sort(np.roots(np.array([A, B, C, D])))

s2P = np.array([s[0], s[1], np.sqrt(np.abs(z[0]))])
s2S = np.array([s[0], s[1], np.sqrt(np.abs(z[1]))])
s2T = np.array([s[0], s[1], np.sqrt(np.abs(z[2]))])
print('s2P', s2P)
print('s2T', s2S)
print('s2S', s2T)

s2P [ 0.00019952  0.00011519  0.0002779 ]
s2T [ 0.00019952  0.00011519  0.00065939]
s2S [ 0.00019952  0.00011519  0.00084074]


In [1649]:
########################################
# POLARIZATION VECTORS OF REFLECTED WAVES
########################################

# Construct the Christoffel matrices for the three upper phases,
# and compute the eigensystem of the matrices.

##### REFLECTED QUASI-P PHASE
CM1P = christoffel(C1, s1P)
w, v = np.linalg.eig(CM1P)
w = eigvec3symm(CM1P, p1)
ev1P = w / np.abs(np.sqrt(w.dot(w)))

##### REFLECTED QUASI-S PHASE
CM1S = christoffel(C1, s1S)
w, v = np.linalg.eig(CM1S)
ev1S = w / np.abs(np.sqrt(w.dot(w)))

##### REFLECTED QUASI-T PHASE
CM1T = christoffel(C1, s1T)
w, v = np.linalg.eig(CM1T-p1*np.identity(3))
ev1T = w / np.abs(np.sqrt(w.dot(w)))

# Match up quasi-SV and quasi-SH with the proper eigenvalues/eigenvectors
if np.sum(ev1T*n) > np.sum(ev1S*n):
    print('swapping upper shears')
    foo = s1S
    s1S = s1T
    s1T = foo
    
    foo = ev1S
    ev1S = ev1T
    ev1T = foo
    
##### QC Output
print('CM1P', CM1P)

CM1P [[ 815.94896974  219.48138705  457.40116402]
 [ 219.48138705  464.83762115  267.5595924 ]
 [ 457.40116402  267.5595924   815.30734418]]


In [1650]:
########################################
# POLARIZATION VECTORS OF TRANSMITTED WAVES
########################################

##### LOWER LAYER P PHASE
CM2P = christoffel(C2, s2P)
w, v = np.linalg.eig(CM)
ev2P = w / np.abs(np.sqrt(w.dot(w)))

##### LOWER LAYER S PHASE
CM2S = christoffel(C2, s2S)
w, v = np.linalg.eig(CM)
ev2S = w / np.abs(np.sqrt(w.dot(w)))

##### LOWER LAYER T PHASE
CM2T = christoffel(C2, s2T)
w, v = np.linalg.eig(CM)
ev2T = w / np.abs(np.sqrt(w.dot(w)))

# Match up quasi-SV and quasi-SH with the proper eigenvalues/eigenvectors
if np.sum(ev2T*n) > np.sum(ev2S*n):
    print('swapping lower shears')
    foo = s2S
    s2S = s2T
    s2T = foo
    
    foo = ev2S
    ev2S = ev2T
    ev2T = foo

In [1651]:
# Construct X, Y, X', and Y' impedance matrices

##### UPPER MEDIUM
X1 = np.zeros(shape=(3, 3))
X1[0][0] = ev1P[0]
X1[0][1] = ev1S[0]
X1[0][2] = ev1T[0]
X1[1][0] = ev1P[1]
X1[1][1] = ev1S[1]
X1[1][2] = ev1T[1]
X1[2][0] = -(C1[0][2]+C1[2][5])*s1P[0] - (C1[1][2]+C1[2][5])*s1P[1] - C1[2][2]*ev1P[2]*s1P[2]
X1[2][1] = -(C1[0][2]+C1[2][5])*s1S[0] - (C1[1][2]+C1[2][5])*s1S[1] - C1[2][2]*ev1S[2]*s1S[2]
X1[2][2] = -(C1[0][2]+C1[2][5])*s1T[0] - (C1[1][2]+C1[2][5])*s1T[1] - C1[2][2]*ev1T[2]*s1T[2]

Y1 = np.zeros(shape=(3, 3))
Y1[0][0] = -(C1[4][4]*s1P[0] + C1[3][4]*s1P[1])*ev1P[2] - (C1[4][4]*ev1P[0] + C1[3][4]*ev1P[1])*s1P[2]
Y1[0][1] = -(C1[4][4]*s1S[0] + C1[3][4]*s1S[1])*ev1S[2] - (C1[4][4]*ev1S[0] + C1[3][4]*ev1S[1])*s1S[2]
Y1[0][2] = -(C1[4][4]*s1T[0] + C1[3][4]*s1T[1])*ev1T[2] - (C1[4][4]*ev1T[0] + C1[3][4]*ev1T[1])*s1T[2]
Y1[1][0] = -(C1[3][4]*s1P[0] + C1[3][3]*s1P[1])*ev1P[2] - (C1[3][4]*ev1P[0] + C1[3][3]*ev1P[1])*s1P[2]
Y1[1][1] = -(C1[3][4]*s1S[0] + C1[3][3]*s1S[1])*ev1S[2] - (C1[3][4]*ev1S[0] + C1[3][3]*ev1S[1])*s1S[2]
Y1[1][2] = -(C1[3][4]*s1T[0] + C1[3][3]*s1T[1])*ev1T[2] - (C1[3][4]*ev1T[0] + C1[3][3]*ev1T[1])*s1T[2]
Y1[2][0] = ev1P[2]
Y1[2][1] = ev1S[2]
Y1[2][2] = ev1T[2]

##### LOWER MEDIUM
X2 = np.zeros(shape=(3, 3))
X2[0][0] = ev2P[0]
X2[0][1] = ev2S[0]
X2[0][2] = ev2T[0]
X2[1][0] = ev2P[1]
X2[1][1] = ev2S[1]
X2[1][2] = ev2T[1]
X2[2][0] = -(C2[0][2]+C2[2][5])*s2P[0] - (C2[1][2]+C2[2][5])*s2P[1] - C2[2][2]*ev2P[2]*s2P[2]
X2[2][1] = -(C2[0][2]+C2[2][5])*s2S[0] - (C2[1][2]+C2[2][5])*s2S[1] - C2[2][2]*ev2S[2]*s2S[2]
X2[2][2] = -(C2[0][2]+C2[2][5])*s2T[0] - (C2[1][2]+C2[2][5])*s2T[1] - C2[2][2]*ev2T[2]*s2T[2]

Y2 = np.zeros(shape=(3, 3))
Y2[0][0] = -(C2[4][4]*s2P[0] + C2[3][4]*s2P[1])*ev2P[2] - (C2[4][4]*ev2P[0] + C2[3][4]*ev2P[1])*s2P[2]
Y2[0][1] = -(C2[4][4]*s2S[0] + C2[3][4]*s2S[1])*ev2S[2] - (C2[4][4]*ev2S[0] + C2[3][4]*ev2S[1])*s2S[2]
Y2[0][2] = -(C2[4][4]*s2T[0] + C2[3][4]*s2T[1])*ev2T[2] - (C2[4][4]*ev2T[0] + C2[3][4]*ev2T[1])*s2T[2]
Y2[1][0] = -(C2[3][4]*s2P[0] + C2[3][3]*s2P[1])*ev2P[2] - (C2[3][4]*ev2P[0] + C2[3][3]*ev2P[1])*s2P[2]
Y2[1][1] = -(C2[3][4]*s2S[0] + C2[3][3]*s2S[1])*ev2S[2] - (C2[3][4]*ev2S[0] + C2[3][3]*ev2S[1])*s2S[2]
Y2[1][2] = -(C2[3][4]*s2T[0] + C2[3][3]*s2T[1])*ev2T[2] - (C2[3][4]*ev2T[0] + C2[3][3]*ev2T[1])*s2T[2]
Y2[2][0] = ev2P[2]
Y2[2][1] = ev2S[2]
Y2[2][2] = ev2T[2]

In [1653]:
# Solve the X, Y, X', Y' system of equations for the Zoeppritz reflection matrix R
D = inv(X1)*X2 + inv(Y1)*Y2
R = (inv(X1)*X2 - inv(Y1)*Y2)*inv(D)

print(R[0][0])

0.140960937553
